2025-02-02 15:47:15,631 - INFO - Namespace(device='cuda:3', channel_weights=[1.0, 2.0, 1.0, 1.0], batch_size=8, num_classes=4, pretrained=False, pretrained_weights='./Synapse_weights_1u1d', lr=0.0001, epochs=500, warmup_epochs=10, dataset_mode='ACDC', max_channel=256, l2_norm=1e-07, patience=15, aug=False, wandb=True, cache=True, log_dir='../../de_logistics/ACDC_1UNetlinear_02-02-15-47-14/', log_file_path='../../de_logistics/ACDC_1UNetlinear_02-02-15-47-14/training.log')
Epoch 1/500 [Training]:   0%|                                                                       | 0/75 [00:02<?, ?batch/s]
Traceback (most recent call last):
  File "/data2/lyw/deunet_mem_based/train.py", line 218, in <module>
    main(args, net)
  File "/data2/lyw/deunet_mem_based/train.py", line 69, in main
    train_acc, train_losses = train_epoch(args, net, optimizer, train_loader, device, epoch, scheduler)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/lyw/deunet_mem_based/train.py", line 140, in train_epoch
    train_losses, train_acc, _= process_epoch(args, net, train_loader, device, 'train', optimizer, scaler, scheduler)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/lyw/deunet_mem_based/train.py", line 109, in process_epoch
    loss = evaluator.loss()
           ^^^^^^^^^^^^^^^^
  File "/data2/lyw/deunet_mem_based/utils/metrics.py", line 222, in loss
    return self.dice_loss() + 10*self.focal_loss()
           ^^^^^^^^^^^^^^^^
  File "/data2/lyw/deunet_mem_based/utils/metrics.py", line 211, in dice_loss
    dice_loss_val_weighted = self.dice_loss_func(self.pred, self.label_one_hot)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lyw/anaconda3/envs/unet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lyw/anaconda3/envs/unet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/lyw/deunet_mem_based/utils/metrics.py", line 111, in forward
    dice_loss = dice(predict[:, i], target[:, i])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lyw/anaconda3/envs/unet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lyw/anaconda3/envs/unet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/lyw/deunet_mem_based/utils/metrics.py", line 66, in forward
    predict = predict.contiguous().view(predict.shape[0], -1)
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'numpy.ndarray' object has no attribute 'contiguous'
