2025-02-02 16:45:35,894 - INFO - Namespace(device='cuda:3', channel_weights=[1.0, 2.0, 1.0, 1.0], batch_size=8, num_classes=4, pretrained=False, pretrained_weights='./Synapse_weights_1u1d', lr=0.0001, epochs=500, warmup_epochs=10, dataset_mode='ACDC', max_channel=256, l2_norm=1e-07, patience=15, aug=False, wandb=True, cache=True, log_dir='../../de_logistics/ACDC_3UNetlinear_02-02-16-45-34/', log_file_path='../../de_logistics/ACDC_3UNetlinear_02-02-16-45-34/training.log')
Epoch 1/500 [Training]:   0%|                                                                             | 0/75 [00:01<?, ?batch/s]
Traceback (most recent call last):
  File "/data2/lyw/deunet_mem_based/train.py", line 221, in <module>
    main(args, net)
  File "/data2/lyw/deunet_mem_based/train.py", line 69, in main
    train_acc, train_losses = train_epoch(args, net, optimizer, train_loader, device, epoch, scheduler)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/lyw/deunet_mem_based/train.py", line 140, in train_epoch
    train_losses, train_acc, _= process_epoch(args, net, train_loader, device, 'train', optimizer, scaler, scheduler)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/lyw/deunet_mem_based/train.py", line 107, in process_epoch
    pred = net(image, valid_mask)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lyw/anaconda3/envs/unet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lyw/anaconda3/envs/unet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/lyw/deunet_mem_based/model/DE_framework.py", line 112, in forward
    base_learner_output = model(img_)
                          ^^^^^^^^^^^
  File "/home/lyw/anaconda3/envs/unet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lyw/anaconda3/envs/unet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/lyw/deunet_mem_based/model/unet.py", line 122, in forward
    x = self.up3(x, x2)
        ^^^^^^^^^^^^^^^
  File "/home/lyw/anaconda3/envs/unet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lyw/anaconda3/envs/unet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/lyw/deunet_mem_based/model/unet.py", line 67, in forward
    return self.conv(x)
           ^^^^^^^^^^^^
  File "/home/lyw/anaconda3/envs/unet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lyw/anaconda3/envs/unet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/lyw/deunet_mem_based/model/unet.py", line 23, in forward
    return self.double_conv(x)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/lyw/anaconda3/envs/unet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lyw/anaconda3/envs/unet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lyw/anaconda3/envs/unet/lib/python3.11/site-packages/torch/nn/modules/container.py", line 250, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/home/lyw/anaconda3/envs/unet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lyw/anaconda3/envs/unet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lyw/anaconda3/envs/unet/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 554, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lyw/anaconda3/envs/unet/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 549, in _conv_forward
    return F.conv2d(
           ^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 224.00 MiB. GPU 3 has a total capacity of 23.68 GiB of which 184.88 MiB is free. Process 1243001 has 19.68 GiB memory in use. Including non-PyTorch memory, this process has 3.76 GiB memory in use. Of the allocated memory 3.40 GiB is allocated by PyTorch, and 133.46 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
